name: Pulumi
on:
  push:
    branches:
      - master
jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm update
      - run: npm install -g @angular/cli
      - run: pwd
      - uses: actions/checkout@v2

      - name: Install Angular dependenices
        run: npm install
        working-directory: ./aws-python/frontend/pulumi-app
      - name: Create Pulumi venv
        id: pulumi-venv
        run: python3 -m venv venv
        working-directory: ./aws-python
      - name: Install Pulumi Dependencies
        id: pulumi-deps
        run: |
           source venv/bin/activate
           pip3 install -r requirements.txt
        working-directory: ./aws-python
      - name: Build
        run: ng build
        working-directory: ./aws-python/frontend/pulumi-app
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: ./aws-python
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}