name: Pulumi
on:
  push:
    branches:
      - master
jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      - name: Setup Node
      - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
        with:
          node-version: '12.x'
      - name: Install Angular
        run: npm install -g @angular/cli
      - name: Build Angular
        working-directory: ./aws-python/frontend/pulumi-app
        run: ng build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          work-dir: ./aws-python
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
     

