name: Pulumi
on:
  push:
    branches:
      - master
jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm update
      - run: npm install -g @angular/cli
      - run: npm install --save-dev @angular-devkit/build-angular
      - run: pwd
      - uses: actions/checkout@v2
      - name: Install Angular dependenices
        run: npm install
      - name: Build
        run: ng build
        working-directory: ./aws-python/frontend/pulumi-app
       
      
      
      

